name: flutter_map_picker
description: This package allows you to pick a point, a circle or a custom area in Google Maps
version: 0.1.2
author: Luis Barba <lymtechx@gmail.com>
homepage: https://lymtechx.com/
repository: https://github.com/lymtechx/flutter_map_picker
issue_tracker: https://github.com/lymtechx/flutter_map_picker/issues

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_google_places: ^0.2.4
  google_maps_flutter: ^0.5.25
  google_maps_utils: ^1.2.0+3
  location: ^2.3.5
  geocoder: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
